# Generated by Django 4.1.7 on 2023-11-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('level', models.SmallIntegerField(choices=[(1, 'S'), (2, 'A'), (3, 'B'), (4, 'C')], default=4, verbose_name='级别')),
                ('status', models.SmallIntegerField(choices=[(1, '已占有'), (2, '未使用')], default=2, verbose_name='状态')),
            ],
        ),
    ]
