# Generated by Django 4.1.7 on 2023-12-10 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='书名')),
                ('author', models.CharField(max_length=32, verbose_name='作者')),
                ('publisher', models.CharField(max_length=32, verbose_name='出版商')),
                ('time', models.DateField(verbose_name='出版日期')),
                ('bookleft', models.IntegerField(verbose_name='在馆图书')),
                ('booktotal', models.IntegerField(verbose_name='总数')),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('departname', models.CharField(max_length=32, verbose_name='系名')),
                ('grade', models.IntegerField(verbose_name='年级')),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(verbose_name='借阅日期')),
                ('return_date', models.DateField(verbose_name='应还日期')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.book', verbose_name='书名')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.reader', verbose_name='借阅人')),
            ],
        ),
    ]
