# Generated by Django 4.1.7 on 2023-12-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_book_reader_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='renewed',
            field=models.IntegerField(default=0, verbose_name='续借'),
        ),
    ]
